CLASS zadcl_visitante DEFINITION
  PUBLIC

  CREATE PUBLIC INHERITING FROM zadcl_pessoa.

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZADCL_VISITANTE IMPLEMENTATION.
ENDCLASS.